### ISSUE TITLE
Pantheon desktop

### ISSUE THREAD

**Issue by hedwigz** [NathanCastle/BootShellCredentialProvider#3]
Hi, I am trying to install elementary/pantheon desktop.  
I have install elementary-desktop from the relevant PPA's but I have no clue of the right configuration  
to start a pantheon session. any command I'm trying such as ```startx /usr/bin/gnome-session --session=pantheon``` isn't working.  
Any chance I could get some help?

**Comment by psharma04** [comment]
The X Server is already running, so I don't believe startx is necessary. Instead try: `exec /usr/bin/gnome-session --session=pantheon`
